replicaCount: 2

image:
  repository: 097733790606.dkr.ecr.us-east-1.amazonaws.com/authcloud
  tag: "latest"

service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 30001
  
resources:
  requests:
    cpu: "500m"   # 0.5 vCPU
    memory: "1Gi"  # 1 GiB
  limits:
    cpu: "1"      # 1 vCPU
    memory: "2Gi"  # 2 GiB
