replicaCount: 2

image:
  repository: 097733790606.dkr.ecr.us-east-1.amazonaws.com/authcloud
  tag: "latest"

service:
  type: NodePort
  port: 80
  nodePort: 30001

resources:
  requests:
    memory: "256Mi"  # Memória solicitada
    cpu: "250m"  # CPU solicitada
  limits:
    memory: "512Mi"  # Memória limite
    cpu: "500m"  # CPU limite

