replicaCount: 2

image:
  repository: 097733790606.dkr.ecr.us-eat-1.amazonaws.com/auth-cloud
  tag: "latest"

service:
  type: LoadBalancer
  port: 80

resources:
  requests:
    memory: "128Mi"
    cpu: "500m"
  limits:
    memory: "256Mi"
    cpu: "1000m"
