replicaCount: 2

image:
  repository: 097733790606.dkr.ecr.us-east-1.amazonaws.com/authcloud
  tag: "latest"

service:
  type: NodePort
  port: 80
  nodePort: 30002
  albarn: "arn:aws:elasticloadbalancing:us-east-1:097733790606:loadbalancer/app/authcloud-load-balancer/12414d25035e73e7"

resources:
  requests:
    cpu: "256m"   # 0.25 vCPU
    memory: "512Mi"  # 512 MiB
  limits:
    cpu: "512m"   # 0.5 vCPU
    memory: "1Gi"  # 1 GB

