apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-cloud
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: auth-cloud
  template:
    metadata:
      labels:
        app: auth-cloud
    spec:
      containers:
      - name: auth-cloud
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
---
apiVersion: v1
kind: Service
metadata:
  name: auth-cloud
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  selector:
    app: auth-cloud
