apiVersion: v1
kind: Service
metadata:
  name: "authcloud-service"
  namespace: "authcloud-api"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort | default (randInt 30000 32767) }}
  selector:
    app: "authcloud"
