apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Release.Name }}-test"
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-delete-policy": before-hook-creation  # Remove o pod após a execução do teste
spec:
  containers:
  - name: authcloud-test
    image: curlimages/curl:latest  # Usando a imagem do Curl para testar o endpoint
    command: ["/bin/sh", "-c"]
    args:
      - |
        # Espera o serviço estar pronto antes de testar
        until nslookup authcloud-service; do echo waiting for authcloud-service; sleep 2; done;
        # Faz uma requisição para o serviço
        curl -f http://authcloud-service:80 || exit 1
  restartPolicy: Never
