name: 1-Feature

on:
  push:
    branches:
      - feat**  # Aciona o workflow em branches que começam com "feat"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore src/app/authcloud.csproj

      - name: Build application
        run: dotnet build src/app/authcloud.csproj --configuration Release --no-restore

      - name: Run tests and collect coverage
        run: dotnet test --configuration Release --collect:"XPlat Code Coverage" src/app/authcloud.csproj --no-build --verbosity normal

      - name: Install report generator tool
        run: dotnet tool install --global dotnet-reportgenerator-globaltool

      - name: Publish coverage results
        run: reportgenerator -reports:$(pwd)/**/coverage.cobertura.xml -targetdir:coveragereport -reporttypes:Html
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: 1

      - name: Upload coverage results
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coveragereport/
