name: 1-Feature

on:
  push:
    branches:
      - feat**  # Aciona o workflow em branches que começam com "feat"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        working-directory: src/app/
        run: dotnet restore 

      - name: Build application
        working-directory: src/app/
        run: dotnet build --configuration Release --no-restore

      - name: Run tests and collect coverage
        run: dotnet test src/unit-tests/authcloud.UnitTests.csproj --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=coverage/coverage.opencover.xml

      - name: Install report generator tool
        run: dotnet tool install --global dotnet-reportgenerator-globaltool
        
      - name: List project structure
        run: find .

      - name: Publish coverage results
        run: reportgenerator -reports:coverage/coverage.opencover.xml -targetdir:coverage_report -reporttypes:Html
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: 1

      - name: List project structure
        run: find .

      - name: Upload coverage results
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage_report
