name: 2-Build .NET and Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Package .NET 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore Dependencies
      run: dotnet restore src/app/authcloud.csproj

    - name: Build Application
      run: dotnet build src/app/authcloud.csproj --configuration Release --no-restore

    - name: Run Unit Tests
      run: dotnet test src/unit-tests/authcloud.UnitTests.csproj --configuration Release --no-build --verbosity normal


  # Job para criar imagem Docker e fazer Push no ECR
  docker:
    runs-on: ubuntu-latest
    needs: build
  
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
  
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
  
      - name: Build Docker image
        run: |
          docker build -t authcloud:latest .
          $(aws ecr get-login-password --region ${{ secrets.AWS_REGION }}) | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
          docker tag authcloud:latest ${AWS_ACCOUNT_ID}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/authcloud:latest
  
      - name: Push Docker image to ECR
        run: |
          docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/authcloud:latest
  